name: Auto Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'v')
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 构建模块
        run: |
          cd ./src
          python -m pip install build
          python -m build

      - name: 提取Commit信息
        id: extract
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          python release.py "$commit_message"

      - name: 创建新的Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.tag }}
          body_path: release_body.txt

      - name: 发布PYPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: src/dist/
